version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      - RABBIT_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge