services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: always
    environment:
      - RABBIT_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    ports:
      - 3310:3310
    expose:
      - 3310
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge