server:
  port: 8100
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
        #        increase wait 1s, 3s, 5s...
        enable-exponential-backoff: true
      default:
        max-attempts: 3
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    schemas: book_service
    user: root
    password: admin123
    locations: classpath:db/migration

logging:
  level:
    org.flywaydb: DEBUG

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  zipkin:
    base-url: http://localhost:9411
    # Enable Zipkin to collect and forward to RabbitMQ
    sender:
      type: rabbit
    rabbitmq:
      addresses: localhost:5672
      username: guest
      password: guest
      virtual-host: /

#configuration for swagger and apigateway
springdoc:
  show-actuator: true
  api-docs:
    path: /book-service/v3/api-docs