server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    schemas: cambio_service
    user: root
    password: admin123
    locations: classpath:db/migration

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  zipkin:
    base-url: http://localhost:9411
    # Enable Zipkin to collect and forward to RabbitMQ
    sender:
      type: rabbit
    rabbitmq:
      addresses: rabbit-mq:5672
      username: guest
      password: guest
      virtual-host: /

#configuration for swagger and apigateway
springdoc:
  show-actuator: false
  api-docs:
    path: /cambio-service/v3/api-docs