server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    user: root
    password:

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  zipkin:
    base-url: http://localhost:9411
    # Enable Zipkin to collect and forward to RabbitMQ
    collector:
      rabbitmq:
        enabled: true
        uri: amqp://guest:guest@localhost:5672  # Adjust this URI if needed
        queue: zipkin
        exchange: zipkin
        # Optional configuration: configure message TTL, prefetch, etc.
        message-ttl: 60000
        prefetch-count: 100
  metrics:
    export:
      simple:

#configuration for swagger and apigateway
springdoc:
  show-actuator: false
  api-docs:
    path: /cambio-service/v3/api-docs