server:
  port: 8765
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
# routes configured in ApiGatewayConfig
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: cambio-service
        uri: lb://cambio-service
        predicates:
        - Path=/cambio-service/**
      - id: book-service
        uri: lb://book-service
        predicates:
          - Path=/book-service/**
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /book-service/v3/api-docs
        name: Book Service
        primaryName: Book Service
      - url: /cambio-service/v3/api-docs
        name: Cambio Service
        primaryName: Cambio Service

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  zipkin:
    base-url: http://localhost:9411
    # Enable Zipkin to collect and forward to RabbitMQ
    sender:
      type: rabbit
    rabbitmq:
      addresses: localhost:5672
      username: guest
      password: guest
      virtual-host: /