server:
  port: 8888

spring:
  application:
    name: config-server
  #    when running locally
  #  profiles:
  #    active:
  #      - native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iararmsantos/config-server-sample
#          for private repositories
#          username:
#          password:
          default-label: main
          search-paths:
            - 'greeting-service*'